
spring:
  application:
    name: mvc-demo
  datasource:
    url: jdbc:h2:mem:mvc-demo-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
  mvc:
    hidden-method:
      filter:
        enabled: true